# Generated by Django 4.1 on 2022-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('formats', models.CharField(choices=[('pdf', 'Pdf'), ('json', 'Json'), ('xml', 'Xml')], max_length=256)),
                ('destinations', models.CharField(choices=[('local_drive', 'Local Drive'), ('ftp', 'Ftp'), ('s3', 'S3')], max_length=256)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
